/* eslint-disable react/jsx-no-undef */
/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import OurCommunity from "../../components/about-us/OurCommunity";
import OurVision from "../../components/about-us/OurVision";
import WhoWeAre from "../../components/about-us/WhoWeAre";
import Menu from "../../components/home/menu";
import wline from "/public/white_line.png";

export default function AboutUs() {
  return (
    <div>
      <Head>
        <title>ORIGINS - Riparian Ecosystem Restoration</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col relative justify-center items-center bg-[#EBEBEB] h-full font-Ambit">
        <Image
          className="w-full absolute top-0 h-auto bg-cover bg-center bg-no-repeat"
          src="/bg-about-us.jpg"
          layout="fill"
          sizes="100hw"
          objectPosition="center"
          alt="Background"
        />
        <Menu />
        <Image
          src={wline}
          alt="Separator"
          className="mx-auto w-3/4 absolute top-20 mt-5 md:mt-10 rounded-full z-20 h-[0.1rem]"
        />
        <div className="pt-[9rem]">
          <WhoWeAre />
          <OurVision />
          <OurCommunity />
        </div>
      </main>
    </div>
  );
}
