/* eslint-disable react/jsx-no-undef */
/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import AboutUs from "../components/home/AboutUs";
import ContactUs from "../components/home/ContactUs";
import Intro from "../components/home/Intro";
import OurProjects from "../components/home/OurProjects";
import OurServices from "../components/home/OurServices";
import Testimonials from "../components/home/Testimonials";

export default function Home() {
  return (
    <div>
      <Head>
        <title>ORIGINS - Riparian Ecosystem Restoration</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col justify-center items-center bg-[#EBEBEB] h-full font-Ambit">
        <div>
          <Intro />
          <div className="pt-40 md:pt-[25rem] xl:pt-[1rem] 2xl:pt-[25rem] 3xl:pt-[15rem]">
            <AboutUs />
          </div>
          <OurServices />
          <div className="w-fit">
            <OurProjects />
          </div>
          <Testimonials />
          <ContactUs />
          <p className="text-center pb-10">
            Made with ❤, by{" "}
            <a
              href="https://fr.linkedin.com/in/victor-raguin"
              target="_blank"
              rel="noreferrer"
              className="underline">
              Victor
            </a>
          </p>
        </div>
      </main>
    </div>
  );
}
